image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - push
  - deploy
  - cleanup
build:
  stage: build
  script:
    - echo "build:build"
    - docker login registry.gitlab.com -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF .
    - docker push registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF
unittests:
  stage: test
  script:
    - echo "unittest:test"
    - apk add --no-cache py-pip      
    - pip install docker-compose     
    - docker pull registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF
    - docker tag registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF registry.gitlab.com/jankubierecki/uekpartnership:latest
    - docker-compose pull
    - docker-compose up -d postgres django
    - ./wait_for_container.py django postgres nginx
    - sleep 10s*
    - docker ps -q  --filter status=running --filter name=postgres
    - docker exec uekpartnership_django_1 /partnerships/manage.py test
coverage:
  stage: test
  script:
    - echo "this is coverage"
    - echo $CI_BUILD_REF
push:
  stage: push
  script:
    - echo "this is push"
deploy_test:
  stage: deploy
  script:
    - echo "this is deploy_"
  only:
    - master
  environment: 
    name: test
deploy_staging:
  stage: deploy
  script:
    - echo "this is deploy"
  when: manual
  environment:
    name: staging
cleanup:
  stage: cleanup
  script:
    - echo "this is cleanup"
  when: always
