image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - push
  - deploy_test
  - integration_test
  - deploy

build:
  stage: build
  script:
    - echo "BUILD:build"
    - docker login registry.gitlab.com -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF .
    - docker push registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF
unittests:
  stage: test
  script:
    - echo "TEST:unittests"
    - apk add --no-cache python3
    - apk add --no-cache py3-pip
    - pip3 install --upgrade pip
    - pip3 install docker-compose
    - export PYTHONUNBUFFERED=1
    - docker pull registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF
    - docker tag registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF registry.gitlab.com/jankubierecki/uekpartnership:latest
    - docker-compose pull postgres
    - docker-compose -p uekpartnership up -d postgres django
    - docker ps
    - python3 wait_for_container.py django postgres
    - docker logs --details $(docker inspect --format='{{.Name}}' $(docker ps -aq --no-trunc) | cut -c2- | grep postgres)
    - ./wait_for_postgres.sh
    - docker-compose exec -T django /partnerships/run_tests.sh

push:
  stage: push
  script:
    - echo "PUSH:push"
    - docker login registry.gitlab.com -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker pull registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF
    - docker tag registry.gitlab.com/jankubierecki/uekpartnership:$CI_BUILD_REF registry.gitlab.com/jankubierecki/uekpartnership:latest
    - docker push registry.gitlab.com/jankubierecki/uekpartnership:latest

deploy_test:
  stage: deploy_test
  script:
    - echo "DEPLOY:deploy_test"
    - apk add --update --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$TEST_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./docker-compose.yml ./restart_docker.sh root@kubierecki.pl:/root/UEKPartnership/
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@kubierecki.pl "/root/UEKPartnership/restart_docker.sh"

  only:
    - master
  environment: 
    name: test

integration_test:
  image: python:3.6
  stage: integration_test
  script:
    - echo "INTEGRATION_TEST:test"
    - curl https://kubierecki.pl

deploy_staging:
  stage: deploy
  script:
    - echo "DEPLOY:deploy_staging"
  when: manual
  environment:
    name: staging

deploy_production:
  stage: deploy
  script:
    - echo "DEPLOY:deploy_production"
  when: manual
  environment:
    name: production