version: "3.3"
services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - /etc/postgres/data:/var/lib/postgresql/data
  django:
    image: registry.gitlab.com/jankubierecki/uekpartnership:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - static:/partnerships/static
      - /var/log/gunicorn:/var/log/gunicorn
    env_file:
      - ".env"
volumes:
  static:
