# Generated by Django 2.0.6 on 2018-07-30 21:03

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(default=' ', max_length=50, validators=[company.validators.validate_email], verbose_name='Email do firmy'),
        ),
        migrations.AlterField(
            model_name='companycontactperson',
            name='email',
            field=models.EmailField(default=' ', max_length=50, validators=[company.validators.validate_email], verbose_name='Email'),
        ),
    ]
