# Generated by Django 2.0.5 on 2018-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactperson',
            name='email',
            field=models.EmailField(default='example@net.com', max_length=50, verbose_name='Email'),
        ),
    ]
