# Generated by Django 2.0.6 on 2018-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180730_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe Informacje'),
        ),
    ]
