# Generated by Django 2.0.6 on 2018-09-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180913_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_contact_persons',
            field=models.ManyToManyField(through='company.CompanyToCompanyContactPerson', to='company.CompanyContactPerson'),
        ),
        migrations.AlterField(
            model_name='companytocompanycontactperson',
            name='company_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.CompanyContactPerson', verbose_name='Osoba do kontaktu Firmy współpracującej'),
        ),
    ]
