# Generated by Django 2.0.5 on 2018-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180614_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
