# Generated by Django 2.0.5 on 2018-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180614_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactperson',
            name='email',
            field=models.EmailField(default=' ', max_length=50, verbose_name='Email'),
        ),
    ]
