# Generated by Django 2.0.6 on 2018-10-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180914_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companytocompanycontactperson',
            unique_together={('company', 'company_contact_person')},
        ),
    ]
