# Generated by Django 2.0.5 on 2018-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180615_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='privacy_email_date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data powiadomienia o przetwarzaniu danych osobowych'),
        ),
        migrations.AlterField(
            model_name='companycontactperson',
            name='privacy_email_date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data powiadomienia o przetwarzaniu danych osobowych'),
        ),
    ]
