# Generated by Django 2.0.5 on 2018-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20180615_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInformedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('created_at', models.DateTimeField(verbose_name='Wysłano maila')),
            ],
            options={
                'verbose_name': 'Powiadomiona osoba',
                'verbose_name_plural': 'Powiadomione osoby',
                'ordering': ['email'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='privacy_email_date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data powiadomienia o przetwarzaniu danych'),
        ),
        migrations.AlterField(
            model_name='companycontactperson',
            name='privacy_email_date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data powiadomienia o przetwarzaniu danych'),
        ),
    ]
