# Generated by Django 2.0.5 on 2018-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20180615_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinformedusers',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
