# Generated by Django 2.0.5 on 2018-05-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicUser',
        ),
    ]
