# Generated by Django 2.0.6 on 2018-09-12 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='Data zawiązania umowy')),
                ('amount_pay', models.FloatField(blank=True, null=True, verbose_name='Kwota w złotówkach')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Numer umowy')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Dodatkowe Informacje')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.Company', verbose_name='Firma')),
                ('institute_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='university.InstituteUnit', verbose_name='Jednostka Współpracująca')),
            ],
            options={
                'verbose_name': 'Umowa',
                'ordering': ['-contract_date'],
                'verbose_name_plural': 'Umowy',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia współpracy')),
                ('last_contact_date', models.DateField(verbose_name='Rok ostatniego kontaktu')),
                ('name', models.CharField(default=' ', max_length=255, verbose_name='Nazwa współpracy')),
                ('type_of_partnership', models.CharField(choices=[('science', 'Naukowa'), ('learning', 'Dydaktyczna'), ('organizational', 'Organizacyjna'), ('training', 'Szkoleniowa')], default='learning', max_length=255, verbose_name='Typ współpracy')),
                ('kind_of_partnership', models.CharField(choices=[('financial', 'Finansowa'), ('non_financial', 'Niefinansowa'), ('barter', 'Barterowa'), ('sponsored', 'Sponsoring')], default='non_financial', max_length=255, verbose_name='Rodzaj współpracy')),
                ('status', models.CharField(choices=[('finished', 'Zakończona'), ('paid_and_on', 'Opłacona - w trakcie'), ('started_not_paid', 'Nieopłacona - w trakcie'), ('other', 'Inna')], default='started_not_paid', max_length=255, verbose_name='Status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('company_contact_persons', models.ForeignKey(help_text='Osoby związane tylko z wybraną wcześniej firmą', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='company.CompanyContactPerson', verbose_name='Osoby Do kontaktu Firmy')),
                ('university_contact_persons', models.ForeignKey(help_text='Osoby związane tylko z wybraną wcześniej jednostką UEK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='university.UniversityContactPerson', verbose_name='Osoby Do kontaktu UEK')),
            ],
            options={
                'verbose_name': 'Współpraca',
                'ordering': ['-start_date'],
                'verbose_name_plural': 'Współprace',
            },
        ),
        migrations.CreateModel(
            name='PartnershipLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizwoano')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utworzono przez')),
                ('partnership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='partnerships.Partnership', verbose_name='Wspolprace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowano przez')),
            ],
            options={
                'verbose_name': 'Notatka',
                'ordering': ['updated_by'],
                'verbose_name_plural': 'Notatki',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='partnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
    ]
