# Generated by Django 2.0.5 on 2018-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0010_auto_20180528_1058'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='Data zawiązania umowy')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Kwota w złotówkach')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Numer umowy')),
                ('additional_info', models.TextField(verbose_name='Dodatkowe Informacje')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.Company', verbose_name='Firmy')),
                ('institute_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='university.InstituteUnit', verbose_name='Jednostki Współpracujące')),
            ],
            options={
                'verbose_name': 'Umowa',
                'verbose_name_plural': 'Umowy',
                'ordering': ['-contract_date'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='Data rozpoczęcia współpracy')),
                ('last_contact_date', models.DateField(verbose_name='Rok ostatniego kontaktu')),
                ('company_contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='company.CompanyContactPerson', verbose_name='Osoby Do kontaktu Firmy')),
                ('university_contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='university.UniversityContactPerson', verbose_name='Osoby Do kontaktu UEK')),
            ],
            options={
                'verbose_name': 'Współpraca',
                'verbose_name_plural': 'Współprace',
                'ordering': ['-contract_date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='partnership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
    ]
