# Generated by Django 2.0.6 on 2018-09-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('university', '0001_initial'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='company_contact_persons',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='university_contact_persons',
        ),
        migrations.AddField(
            model_name='contract',
            name='company_contact_persons',
            field=models.ForeignKey(help_text='Osoby do kontaktu firmy związana z ta umowa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='company.CompanyContactPerson', verbose_name='Osoby Do kontaktu Firmy'),
        ),
        migrations.AddField(
            model_name='contract',
            name='university_contact_persons',
            field=models.ForeignKey(help_text='Osoby związane tylko z wybraną wcześniej jednostką UEK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='university.UniversityContactPerson', verbose_name='Osoby Do kontaktu UEK'),
        ),
    ]
