# Generated by Django 2.0.5 on 2018-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa współpracy'),
        ),
    ]
