# Generated by Django 2.0.5 on 2018-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_partnership_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(default='default', max_length=255, verbose_name='Nazwa współpracy'),
            preserve_default=False,
        ),
    ]
