# Generated by Django 2.0.5 on 2018-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_auto_20180528_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='kinds_of_partnerships',
            field=models.CharField(choices=[('financial', 'Finansowa'), ('non_financial', 'Niefinansowa'), ('barter', 'Barterowa'), ('sponsored', 'Sponsoring')], default='non_financial', max_length=255, verbose_name='Rodzaj współpracy'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='types_of_partnerships',
            field=models.CharField(choices=[('science', 'Naukowa'), ('learning', 'Dydaktyczna'), ('organizational', 'Organizacyjna'), ('training', 'Szkoleniowa')], default='learning', max_length=255, verbose_name='Typ współpracy'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(default='bla', max_length=255, verbose_name='Nazwa współpracy'),
        ),
    ]
