# Generated by Django 2.0.6 on 2018-09-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_auto_20180913_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
    ]
