# Generated by Django 2.0.6 on 2018-09-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180913_2152'),
        ('company', '0003_auto_20180914_1248'),
        ('partnerships', '0004_auto_20180913_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractToCompanyContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('company_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.CompanyContactPerson', verbose_name='Osoba do kontaktu firmy')),
            ],
        ),
        migrations.CreateModel(
            name='ContractToUniversityContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company_contact_persons',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='university_contact_persons',
        ),
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(help_text='Po prawej stronie pokażą się współprace o podobnej nazwie, które są już w systemie', max_length=255, verbose_name='Nazwa współpracy'),
        ),
        migrations.AddField(
            model_name='contracttouniversitycontactperson',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerships.Contract', verbose_name='Umowa'),
        ),
        migrations.AddField(
            model_name='contracttouniversitycontactperson',
            name='university_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='university.UniversityContactPerson', verbose_name='Osoba do kontaktu UEK'),
        ),
        migrations.AddField(
            model_name='contracttocompanycontactperson',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerships.Contract', verbose_name='Umowa'),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_contact_persons',
            field=models.ManyToManyField(help_text='Osoby do kontaktu firmy związane z tą umową', through='partnerships.ContractToCompanyContactPerson', to='company.CompanyContactPerson', verbose_name='Osoby Do kontaktu Firmy'),
        ),
        migrations.AddField(
            model_name='contract',
            name='university_contact_persons',
            field=models.ManyToManyField(help_text='Osoby do kontaktu UEK związane z tą umową', through='partnerships.ContractToUniversityContactPerson', to='university.UniversityContactPerson', verbose_name='Osoby do kontaktu UEK'),
        ),
    ]
