# Generated by Django 2.0.5 on 2018-05-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0004_auto_20180528_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='kinds_of_partnerships',
            new_name='kind_of_partnership',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='types_of_partnerships',
            new_name='type_of_partnership',
        ),
    ]
