# Generated by Django 2.0.5 on 2018-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0005_auto_20180528_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe Informacje'),
        ),
    ]
