# Generated by Django 2.0.5 on 2018-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0007_partnership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('finished', 'Zakończona'), ('paid_and_on', 'Opłacona - w trakcie'), ('started_not_paid', 'Nieopłacona - w trakcie'), ('other', 'Inna')], default=2, max_length=255, verbose_name='Status'),
        ),
    ]
