# Generated by Django 2.0.5 on 2018-06-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_auto_20180603_1516'),
        ('partnerships', '0008_auto_20180603_1347'),
    ]

    operations = [
    ]
