# Generated by Django 2.0.6 on 2018-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180913_2152'),
        ('company', '0004_auto_20181002_1729'),
        ('partnerships', '0008_auto_20181003_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company_contact_persons',
            field=models.ManyToManyField(help_text='Osoby do kontaktu firmy związane z tą umową', to='company.CompanyContactPerson'),
        ),
        migrations.AddField(
            model_name='contract',
            name='university_contact_persons',
            field=models.ManyToManyField(help_text='Osoby do kontaktu UEK związane z tą umową', to='university.UniversityContactPerson', verbose_name='Osoby do kontaktu UEK'),
        ),
    ]
