# Generated by Django 2.0.5 on 2018-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0009_merge_20180603_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('finished', 'Zakończona'), ('paid_and_on', 'Opłacona - w trakcie'), ('started_not_paid', 'Nieopłacona - w trakcie'), ('other', 'Inna')], default='started_not_paid', max_length=255, verbose_name='Status'),
        ),
    ]
