# Generated by Django 2.0.5 on 2018-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0010_auto_20180611_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='institute_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='university.InstituteUnit', verbose_name='Jednostki Współpracujące'),
        ),
    ]
