# Generated by Django 2.0.6 on 2018-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0011_partnership_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(help_text='Pod spodem pokażą się współprace o podobnej nazwie, które są już w systemie', max_length=255, verbose_name='Nazwa współpracy'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('finished', 'Zakończona'), ('unfinished', 'W trakcie')], default='unfinished', max_length=255, verbose_name='Status'),
        ),
    ]
