# Generated by Django 2.0.5 on 2018-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0012_partnershiplogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershiplogentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizwoano'),
        ),
    ]
