# Generated by Django 2.0.6 on 2018-10-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0012_auto_20181013_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
    ]
