# Generated by Django 2.0.6 on 2018-11-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0013_auto_20181013_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
    ]
