# Generated by Django 2.0.5 on 2018-06-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0013_partnershiplogentry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershiplogentry',
            name='partnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='partnerships.Partnership', verbose_name='Wspolprace'),
        ),
    ]
