# Generated by Django 2.0.5 on 2018-06-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0014_partnershiplogentry_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='company_contact_person',
            field=models.ForeignKey(help_text='Osoby związane tylko z wybraną wcześniej firmą', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='company.CompanyContactPerson', verbose_name='Osoby Do kontaktu Firmy'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='university_contact_person',
            field=models.ForeignKey(help_text='Osoby związane tylko z wybraną wcześniej jednostką UEK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='university.UniversityContactPerson', verbose_name='Osoby Do kontaktu UEK'),
        ),
    ]
