# Generated by Django 2.0.5 on 2018-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0015_auto_20180615_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Nazwa współpracy'),
        ),
    ]
