# Generated by Django 2.0.6 on 2018-06-19 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0017_partnership_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partnership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='partnerships.Partnership', verbose_name='Współprace'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
