# Generated by Django 2.0.5 on 2018-05-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Katedra',
                'verbose_name_plural': 'Katedry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstituteUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='instutute_units', to='university.Institute',
                                                verbose_name='Katedra')),
            ],
            options={
                'verbose_name': 'Jednostka Współpracująca UEK',
                'verbose_name_plural': 'Jednostki Współpracująca UEK',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='institute',
            name='university_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes',
                                    to='university.UniversityFaculty', verbose_name='Wydział'),
        ),
    ]
