# Generated by Django 2.0.5 on 2018-06-14 08:42

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycontactperson',
            name='email',
            field=models.EmailField(default='example@net.com', help_text='Tylko z domeną UEK', max_length=50, validators=[university.validators.email_validation], verbose_name='Email'),
        ),
    ]
