# Generated by Django 2.0.5 on 2018-05-23 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteunit',
            options={'ordering': ['institute__name', 'name'], 'verbose_name': 'Jednostka Współpracująca UEK',
                     'verbose_name_plural': 'Jednostki Współpracująca UEK'},
        ),
        migrations.AddField(
            model_name='instituteunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Utworzono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
    ]
