# Generated by Django 2.0.6 on 2018-09-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteunit',
            name='name',
            field=models.CharField(help_text='Po prawej stronie pokażą się jednostki o podobnej nazwie, które są już w systemie', max_length=255, verbose_name='Nazwa'),
        ),
    ]
