# Generated by Django 2.0.6 on 2018-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20180913_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteunittouniversitycontactperson',
            options={'ordering': ['-created_at'], 'verbose_name': 'osoba / jednostka', 'verbose_name_plural': 'osoby / jednostki'},
        ),
        migrations.AlterField(
            model_name='instituteunit',
            name='name',
            field=models.CharField(help_text='Pod spodem pokażą się jednostki o podobnej nazwie, które są już w systemie', max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='universitycontactperson',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
    ]
