# Generated by Django 2.0.5 on 2018-05-23 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_universitycontactperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteunit',
            options={'ordering': ['institute__name', 'name'], 'verbose_name': 'Jednostka Współpracująca UEK', 'verbose_name_plural': 'Jednostki Współpracujące UEK'},
        ),
        migrations.AlterModelOptions(
            name='universitycontactperson',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Osoba do kontaktu', 'verbose_name_plural': 'Osoby do kontaktu'},
        ),
        migrations.AddField(
            model_name='universitycontactperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Utworzono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitycontactperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
    ]
