# Generated by Django 2.0.5 on 2018-06-14 12:12

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20180614_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycontactperson',
            name='email',
            field=models.EmailField(default='example@uek.krakow.pl', help_text='Tylko z domeną UEK', max_length=50, validators=[university.validators.email_validation], verbose_name='Email'),
        ),
    ]
