# Generated by Django 2.0.5 on 2018-05-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20180523_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteUnitToUniversityContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Przypisana katedra',
                'verbose_name_plural': 'Przypisane katedry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='instituteunit',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_units', to='university.Institute', verbose_name='Katedra'),
        ),
        migrations.AddField(
            model_name='instituteunittouniversitycontactperson',
            name='institute_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.InstituteUnit', verbose_name='Jednostka Współpracująca UEK'),
        ),
        migrations.AddField(
            model_name='instituteunittouniversitycontactperson',
            name='university_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.UniversityContactPerson', verbose_name='Osoba do kontaktu'),
        ),
        migrations.AddField(
            model_name='instituteunit',
            name='university_contact_persons',
            field=models.ManyToManyField(through='university.InstituteUnitToUniversityContactPerson', to='university.UniversityContactPerson'),
        ),
    ]
