# Generated by Django 2.0.6 on 2018-06-19 16:25

from django.db import migrations, models
import university.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20180614_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycontactperson',
            name='email',
            field=models.EmailField(help_text='Tylko z domeną UEK', max_length=50, validators=[university.validators.email_validation], verbose_name='Email'),
        ),
    ]
