# Generated by Django 2.0.5 on 2018-05-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20180523_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteunittouniversitycontactperson',
            name='university_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_units', to='university.UniversityContactPerson', verbose_name='Osoba do kontaktu UEK'),
        ),
    ]
