# Generated by Django 2.0.5 on 2018-05-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20180523_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitycontactperson',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Osoba do kontaktu UEK', 'verbose_name_plural': 'Osoby do kontaktu UEK'},
        ),
        migrations.AlterField(
            model_name='instituteunit',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_units', to='university.Institute', verbose_name='Katedra (jeśli związana)'),
        ),
    ]
