# Generated by Django 2.0.5 on 2018-05-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20180524_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituteunittouniversitycontactperson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Przypisana osoba', 'verbose_name_plural': 'Przypisane osoby'},
        ),
        migrations.AlterField(
            model_name='instituteunit',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute_units', to='university.Institute', verbose_name='Katedra (opcjonalnie)'),
        ),
    ]
